import 'package:flutter/material.dart';
import 'package:litapp/models/lit_models.dart';

class MockLitData {
  static AppUser currentUser = AppUser(
    id: 'u1',
    name: 'Bianca',
    handle: '@bianca',
    avatarSeed: 'bianca',
    bio: 'Reads literary fiction, joins monthly club debates, and always circles back to stories with warm, strange hearts.',
    level: 12,
    xp: 1240,
    nextLevelXp: 1500,
    points: 880,
    booksRead: 37,
    pagesRead: 12840,
    averageRating: 4.4,
    favoriteGenres: ['Literary fiction', 'Mystery', 'Fantasy'],
    clubsJoined: 3,
    isAdmin: true,
    streakDays: 18,
  );

  static final users = <AppUser>[
    currentUser,
    AppUser(
      id: 'u2',
      name: 'Luna March',
      handle: '@lunamarch',
      avatarSeed: 'luna',
      bio: 'Prefers quiet cafés, annotated margins, and ambitious time-bending novels.',
      level: 13,
      xp: 1380,
      nextLevelXp: 1600,
      points: 920,
      booksRead: 41,
      pagesRead: 15020,
      averageRating: 4.8,
      favoriteGenres: ['Sci-fi', 'Literary fiction', 'Speculative'],
      clubsJoined: 4,
      isAdmin: false,
      streakDays: 26,
    ),
    AppUser(
      id: 'u3',
      name: 'Clara Finch',
      handle: '@clarafinch',
      avatarSeed: 'clara',
      bio: 'Keeps a color-coded reading journal and loves discussion prompts with emotional depth.',
      level: 11,
      xp: 1120,
      nextLevelXp: 1350,
      points: 870,
      booksRead: 33,
      pagesRead: 10480,
      averageRating: 4.5,
      favoriteGenres: ['Romance', 'Contemporary', 'Memoir'],
      clubsJoined: 2,
      isAdmin: false,
      streakDays: 14,
    ),
    AppUser(
      id: 'u4',
      name: 'Milo Reed',
      handle: '@miloreed',
      avatarSeed: 'milo',
      bio: 'Always in the middle of three books and one friendly debate.',
      level: 9,
      xp: 860,
      nextLevelXp: 1100,
      points: 740,
      booksRead: 24,
      pagesRead: 7850,
      averageRating: 4.1,
      favoriteGenres: ['Thriller', 'Mystery', 'Non-fiction'],
      clubsJoined: 2,
      isAdmin: false,
      streakDays: 8,
    ),
    AppUser(
      id: 'u5',
      name: 'Sofia Vale',
      handle: '@sofiavale',
      avatarSeed: 'sofia',
      bio: 'Loves cozy fantasy, paper textures, and tiny reading rituals.',
      level: 10,
      xp: 980,
      nextLevelXp: 1200,
      points: 690,
      booksRead: 29,
      pagesRead: 9300,
      averageRating: 4.2,
      favoriteGenres: ['Fantasy', 'YA', 'Adventure'],
      clubsJoined: 3,
      isAdmin: false,
      streakDays: 11,
    ),
  ];

  static final books = <Book>[
    Book(
      id: 'b1',
      title: 'Tomorrow, and Tomorrow, and Tomorrow',
      author: 'Gabrielle Zevin',
      synopsis: 'A friendship-centered story of creative ambition, games, and the complicated tenderness of building something together.',
      pages: 400,
      averageRating: 4.3,
      genre: 'Literary fiction',
      coverSeed: 'tomorrow',
      accentColor: const Color(0xFF9381FF),
    ),
    Book(
      id: 'b2',
      title: 'The Midnight Library',
      author: 'Matt Haig',
      synopsis: 'A reflective journey through lives unlived, hope, and the quiet courage of choosing again.',
      pages: 304,
      averageRating: 4.1,
      genre: 'Contemporary fiction',
      coverSeed: 'library',
      accentColor: const Color(0xFFB8B8FF),
    ),
    Book(
      id: 'b3',
      title: 'Piranesi',
      author: 'Susanna Clarke',
      synopsis: 'An atmospheric mystery in an impossible house, where knowledge is fragile and wonder is everywhere.',
      pages: 240,
      averageRating: 4.5,
      genre: 'Fantasy mystery',
      coverSeed: 'house',
      accentColor: const Color(0xFFFFD8BE),
    ),
    Book(
      id: 'b4',
      title: 'The Secret History',
      author: 'Donna Tartt',
      synopsis: 'A dark academic tale of obsession, secrecy, and the polished surface of danger.',
      pages: 559,
      averageRating: 4.4,
      genre: 'Dark academia',
      coverSeed: 'history',
      accentColor: const Color(0xFFFFEEDD),
    ),
    Book(
      id: 'b5',
      title: 'The House in the Cerulean Sea',
      author: 'TJ Klune',
      synopsis: 'A warm, hopeful story about found family, gentle magic, and a house that slowly becomes home.',
      pages: 398,
      averageRating: 4.6,
      genre: 'Cozy fantasy',
      coverSeed: 'sea',
      accentColor: const Color(0xFF9381FF),
    ),
    Book(
      id: 'b6',
      title: 'Lessons in Chemistry',
      author: 'Bonnie Garmus',
      synopsis: 'A sharp, witty story of science, defiance, and a woman whose life refuses to fit the script.',
      pages: 386,
      averageRating: 4.2,
      genre: 'Historical fiction',
      coverSeed: 'chemistry',
      accentColor: const Color(0xFFB8B8FF),
    ),
  ];

  static final clubs = <Club>[
    Club(
      id: 'c1',
      name: 'Lithappened',
      description: 'Editorial discussions, shared reading goals, and a little competitive sparkle.',
      privacy: ClubPrivacy.public,
      memberCount: 12,
      currentBookId: 'b2',
      progress: 72,
      coverSeed: 'lithappened',
      profileSeed: 'club1',
      themeColor: const Color(0xFF9381FF),
      isJoined: true,
    ),
    Club(
      id: 'c2',
      name: 'The Quiet Chapter',
      description: 'A cozy circle for reflective readers who like thoughtful prompts and soft pacing.',
      privacy: ClubPrivacy.private,
      memberCount: 8,
      currentBookId: 'b3',
      progress: 41,
      coverSeed: 'quiet',
      profileSeed: 'club2',
      themeColor: const Color(0xFFB8B8FF),
      isJoined: false,
    ),
    Club(
      id: 'c3',
      name: 'Paper Moon Society',
      description: 'For whimsical readers who love monthly draws, challenges, and richly layered stories.',
      privacy: ClubPrivacy.inviteOnly,
      memberCount: 15,
      currentBookId: 'b1',
      progress: 67,
      coverSeed: 'moon',
      profileSeed: 'club3',
      themeColor: const Color(0xFFFFD8BE),
      isJoined: true,
    ),
  ];

  static final readings = <Reading>[
    Reading(
      id: 'r1',
      bookId: 'b1',
      clubId: 'c3',
      startDate: DateTime(2026, 8, 1),
      endDate: DateTime(2026, 9, 1),
      currentPage: 268,
      totalPages: 400,
      progressPercent: 67,
      status: ReadingStatus.reading,
      membersReading: 9,
      membersFinished: 3,
      averageClubProgress: 64,
      milestones: [
        ReadingMilestone(title: 'START', page: 1, reached: true),
        ReadingMilestone(title: 'Chapter 5', page: 82, reached: true),
        ReadingMilestone(title: 'Chapter 10', page: 164, reached: true),
        ReadingMilestone(title: 'Midpoint', page: 200, reached: true),
        ReadingMilestone(title: 'Final', page: 400, reached: false),
      ],
    ),
    Reading(
      id: 'r2',
      bookId: 'b2',
      clubId: 'c1',
      startDate: DateTime(2026, 8, 5),
      endDate: DateTime(2026, 9, 5),
      currentPage: 218,
      totalPages: 304,
      progressPercent: 72,
      status: ReadingStatus.reading,
      membersReading: 12,
      membersFinished: 7,
      averageClubProgress: 72,
      milestones: [
        ReadingMilestone(title: 'START', page: 1, reached: true),
        ReadingMilestone(title: 'Chapter 5', page: 65, reached: true),
        ReadingMilestone(title: 'Chapter 10', page: 131, reached: true),
        ReadingMilestone(title: 'Midpoint', page: 152, reached: true),
        ReadingMilestone(title: 'Final', page: 304, reached: false),
      ],
    ),
    Reading(
      id: 'r3',
      bookId: 'b3',
      clubId: 'c2',
      startDate: DateTime(2026, 8, 10),
      endDate: DateTime(2026, 9, 10),
      currentPage: 96,
      totalPages: 240,
      progressPercent: 40,
      status: ReadingStatus.reading,
      membersReading: 6,
      membersFinished: 2,
      averageClubProgress: 41,
      milestones: [
        ReadingMilestone(title: 'START', page: 1, reached: true),
        ReadingMilestone(title: 'Chapter 5', page: 48, reached: true),
        ReadingMilestone(title: 'Chapter 10', page: 96, reached: true),
        ReadingMilestone(title: 'Midpoint', page: 120, reached: false),
        ReadingMilestone(title: 'Final', page: 240, reached: false),
      ],
    ),
  ];

  static final achievements = <Achievement>[
    Achievement(id: 'a1', title: 'First Club', description: 'Joined your first reading club.', icon: '📚', points: 50, xp: 100, unlocked: true),
    Achievement(id: 'a2', title: 'Weekend Reader', description: 'Read for 7 days in a row.', icon: '☕', points: 40, xp: 80, unlocked: true),
    Achievement(id: 'a3', title: 'Spoiler Shield', description: 'Handled spoiler comments gracefully.', icon: '🛡️', points: 30, xp: 60, unlocked: true),
    Achievement(id: 'a4', title: 'Discussion Spark', description: 'Left 10 thoughtful comments.', icon: '💬', points: 45, xp: 70, unlocked: true),
    Achievement(id: 'a5', title: 'Book Bloom', description: 'Completed a book with your club.', icon: '🌸', points: 0, xp: 0, unlocked: true),
    Achievement(id: 'a6', title: 'Challenge Runner', description: 'Finished a monthly challenge.', icon: '🏅', points: 65, xp: 100, unlocked: false),
    Achievement(id: 'a7', title: 'Ranking Rise', description: 'Reached the top 3 in monthly rankings.', icon: '✨', points: 80, xp: 150, unlocked: true),
    Achievement(id: 'a8', title: 'Collector', description: 'Unlocked 5 badges.', icon: '🗂️', points: 40, xp: 60, unlocked: false),
    Achievement(id: 'a9', title: 'Page Climber', description: 'Read more than 10,000 pages.', icon: '📖', points: 70, xp: 130, unlocked: true),
    Achievement(id: 'a10', title: 'Curator', description: 'Redeemed a non-monetary reward.', icon: '🎁', points: 75, xp: 110, unlocked: false),
  ];

  static final rewards = <RewardItem>[
    RewardItem(id: 'rw1', name: 'Choose next month\'s book', description: 'Guide the next club pick.', cost: 300, icon: '🗳️', availability: RewardAvailability.available),
    RewardItem(id: 'rw2', name: 'Custom profile badge', description: 'Design a badge that appears on your profile.', cost: 500, icon: '✨', availability: RewardAvailability.available),
    RewardItem(id: 'rw3', name: 'Skip one challenge', description: 'Opt out of a weekly challenge once.', cost: 400, icon: '⏭️', availability: RewardAvailability.limited),
    RewardItem(id: 'rw4', name: 'Special club role for one week', description: 'Become a spotlight host in your club.', cost: 700, icon: '👑', availability: RewardAvailability.available),
    RewardItem(id: 'rw5', name: 'Pick the discussion topic', description: 'Set the next meeting prompt.', cost: 250, icon: '🪄', availability: RewardAvailability.available),
    RewardItem(id: 'rw6', name: 'Priority in book draws', description: 'Get an extra draw entry next month.', cost: 450, icon: '🎲', availability: RewardAvailability.available),
    RewardItem(id: 'rw7', name: 'Reading buddy shoutout', description: 'Feature a friend on your profile.', cost: 220, icon: '💌', availability: RewardAvailability.soldOut),
    RewardItem(id: 'rw8', name: 'Animated shelf frame', description: 'Unlock a decorative shelf for your profile.', cost: 380, icon: '🪩', availability: RewardAvailability.available),
  ];

  static final challenges = <Challenge>[
    Challenge(id: 'ch1', title: 'Read 500 pages in September', description: 'Keep the pace warm and steady.', progress: 320, goal: 500, deadline: DateTime(2026, 9, 30), rewardPoints: 200, status: ChallengeStatus.active),
    Challenge(id: 'ch2', title: 'Finish 2 club books', description: 'Sync your reading with your club schedule.', progress: 1, goal: 2, deadline: DateTime(2026, 9, 15), rewardPoints: 150, status: ChallengeStatus.active),
    Challenge(id: 'ch3', title: 'Leave 5 thoughtful comments', description: 'Add kindness and perspective to the discussion.', progress: 5, goal: 5, deadline: DateTime(2026, 8, 28), rewardPoints: 120, status: ChallengeStatus.completed),
    Challenge(id: 'ch4', title: 'Attend 3 meetings', description: 'Show up for the cozy club rhythm.', progress: 1, goal: 3, deadline: DateTime(2026, 9, 20), rewardPoints: 180, status: ChallengeStatus.upcoming),
    Challenge(id: 'ch5', title: 'Read a debut novel', description: 'Discover a fresh voice and share a reaction.', progress: 0, goal: 1, deadline: DateTime(2026, 10, 1), rewardPoints: 100, status: ChallengeStatus.upcoming),
  ];

  static final events = <EventItem>[
    EventItem(id: 'e1', clubId: 'c1', title: 'Mid-month reflection', description: 'Chapter discussion with spoiler-safe prompts.', dateTime: DateTime(2026, 8, 21, 19, 0), location: 'Video room', type: EventType.meeting, color: const Color(0xFF9381FF)),
    EventItem(id: 'e2', clubId: 'c3', title: 'Reading sprint', description: 'A cozy 45-minute silent sprint.', dateTime: DateTime(2026, 8, 22, 18, 30), location: 'Library café', type: EventType.event, color: const Color(0xFFB8B8FF)),
    EventItem(id: 'e3', clubId: 'c2', title: 'Deadline reminder', description: 'The current reading closes soon.', dateTime: DateTime(2026, 8, 24, 9, 0), location: 'In-app', type: EventType.deadline, color: const Color(0xFFFFD8BE)),
    EventItem(id: 'e4', clubId: 'c1', title: 'Book draw reveal', description: 'Elegantly reveal next month\'s pick.', dateTime: DateTime(2026, 8, 26, 20, 0), location: 'Club board', type: EventType.event, color: const Color(0xFF9381FF)),
    EventItem(id: 'e5', clubId: 'c3', title: 'Challenge launch', description: 'New point challenge goes live.', dateTime: DateTime(2026, 8, 27, 8, 0), location: 'Dashboard', type: EventType.challenge, color: const Color(0xFFB8B8FF)),
    EventItem(id: 'e6', clubId: 'c2', title: 'New member welcome', description: 'Invite-only hello session.', dateTime: DateTime(2026, 8, 29, 18, 0), location: 'Welcome lounge', type: EventType.event, color: const Color(0xFFFFEEDD)),
    EventItem(id: 'e7', clubId: 'c1', title: 'Chapter milestone', description: 'Celebrate the midpoint and spoiler unlock.', dateTime: DateTime(2026, 8, 30, 12, 0), location: 'Reading feed', type: EventType.milestone, color: const Color(0xFFFFD8BE)),
    EventItem(id: 'e8', clubId: 'c3', title: 'Monthly meeting', description: 'Discussion and ranking update.', dateTime: DateTime(2026, 9, 1, 19, 30), location: 'Club room', type: EventType.meeting, color: const Color(0xFF9381FF)),
    EventItem(id: 'e9', clubId: 'c2', title: 'Draw voting', description: 'Vote on the next reading list.', dateTime: DateTime(2026, 9, 2, 17, 0), location: 'Selection panel', type: EventType.event, color: const Color(0xFFB8B8FF)),
    EventItem(id: 'e10', clubId: 'c1', title: 'Reward redemption window', description: 'Redeem points for non-monetary rewards.', dateTime: DateTime(2026, 9, 3, 10, 0), location: 'Rewards store', type: EventType.event, color: const Color(0xFFFFEEDD)),
  ];

  static final notifications = <NotificationItem>[
    NotificationItem(id: 'n1', type: NotificationType.meeting, title: 'New club meeting', body: 'Lithappened scheduled a mid-month reflection.', dateTime: DateTime(2026, 8, 19, 8, 30), unread: true),
    NotificationItem(id: 'n2', type: NotificationType.deadline, title: 'Reading deadline', body: 'Piranesi closes in 4 days.', dateTime: DateTime(2026, 8, 18, 21, 10), unread: true),
    NotificationItem(id: 'n3', type: NotificationType.challenge, title: 'Challenge started', body: 'Read 500 pages in September is now active.', dateTime: DateTime(2026, 8, 18, 9, 0), unread: false),
    NotificationItem(id: 'n4', type: NotificationType.levelUp, title: 'Level up', body: 'You are close to level 13.', dateTime: DateTime(2026, 8, 17, 14, 40), unread: false),
    NotificationItem(id: 'n5', type: NotificationType.achievement, title: 'Achievement unlocked', body: 'Discussion Spark is now yours.', dateTime: DateTime(2026, 8, 17, 10, 15), unread: false),
    NotificationItem(id: 'n6', type: NotificationType.invite, title: 'Club invitation', body: 'Paper Moon Society invited you to a draw.', dateTime: DateTime(2026, 8, 16, 17, 5), unread: true),
    NotificationItem(id: 'n7', type: NotificationType.request, title: 'Join request accepted', body: 'Your request to join The Quiet Chapter was accepted.', dateTime: DateTime(2026, 8, 16, 11, 20), unread: false),
    NotificationItem(id: 'n8', type: NotificationType.book, title: 'New book added', body: 'The House in the Cerulean Sea is available for voting.', dateTime: DateTime(2026, 8, 15, 19, 30), unread: false),
    NotificationItem(id: 'n9', type: NotificationType.event, title: 'Upcoming event', body: 'A reading sprint starts tomorrow evening.', dateTime: DateTime(2026, 8, 15, 10, 0), unread: false),
    NotificationItem(id: 'n10', type: NotificationType.meeting, title: 'Meeting reminder', body: 'Do not forget to update your progress before the session.', dateTime: DateTime(2026, 8, 14, 9, 45), unread: false),
  ];

  static final rankingsMonth = <RankingEntry>[
    RankingEntry(userId: 'u2', name: 'Luna', avatarSeed: 'luna', level: 13, points: 920, rank: 1),
    RankingEntry(userId: 'u3', name: 'Clara', avatarSeed: 'clara', level: 11, points: 870, rank: 2),
    RankingEntry(userId: 'u1', name: 'You', avatarSeed: 'bianca', level: 12, points: 880, rank: 3),
    RankingEntry(userId: 'u5', name: 'Sofia', avatarSeed: 'sofia', level: 10, points: 770, rank: 4),
    RankingEntry(userId: 'u4', name: 'Milo', avatarSeed: 'milo', level: 9, points: 740, rank: 5),
  ];

  static final rankingsYear = <RankingEntry>[
    RankingEntry(userId: 'u2', name: 'Luna', avatarSeed: 'luna', level: 13, points: 3880, rank: 1),
    RankingEntry(userId: 'u1', name: 'You', avatarSeed: 'bianca', level: 12, points: 3520, rank: 2),
    RankingEntry(userId: 'u3', name: 'Clara', avatarSeed: 'clara', level: 11, points: 3410, rank: 3),
    RankingEntry(userId: 'u5', name: 'Sofia', avatarSeed: 'sofia', level: 10, points: 3090, rank: 4),
    RankingEntry(userId: 'u4', name: 'Milo', avatarSeed: 'milo', level: 9, points: 2840, rank: 5),
  ];

  static final rankingsAllTime = <RankingEntry>[
    RankingEntry(userId: 'u2', name: 'Luna', avatarSeed: 'luna', level: 13, points: 8200, rank: 1),
    RankingEntry(userId: 'u3', name: 'Clara', avatarSeed: 'clara', level: 11, points: 7900, rank: 2),
    RankingEntry(userId: 'u1', name: 'You', avatarSeed: 'bianca', level: 12, points: 7640, rank: 3),
    RankingEntry(userId: 'u5', name: 'Sofia', avatarSeed: 'sofia', level: 10, points: 7110, rank: 4),
    RankingEntry(userId: 'u4', name: 'Milo', avatarSeed: 'milo', level: 9, points: 6490, rank: 5),
  ];

  static final comments = <String, List<CommentItem>>{
    'b1': [
      CommentItem(id: 'cmt1', userName: 'Luna', userSeed: 'luna', body: 'The way the narrative handles friendship feels so lived-in and tender.', createdAt: DateTime(2026, 8, 12, 17, 0), spoilerUpToPage: null),
      CommentItem(id: 'cmt2', userName: 'Clara', userSeed: 'clara', body: 'This comment contains spoilers up to page 180. The late-game twist recontextualizes everything beautifully.', createdAt: DateTime(2026, 8, 13, 9, 20), spoilerUpToPage: 180),
      CommentItem(id: 'cmt3', userName: 'Milo', userSeed: 'milo', body: 'The game metaphor lands because the emotional stakes are real, not decorative.', createdAt: DateTime(2026, 8, 14, 8, 45), spoilerUpToPage: null),
    ],
    'b2': [
      CommentItem(id: 'cmt4', userName: 'Sofia', userSeed: 'sofia', body: 'Softly hopeful and exactly the right pace for a club read.', createdAt: DateTime(2026, 8, 10, 16, 10), spoilerUpToPage: null),
      CommentItem(id: 'cmt5', userName: 'You', userSeed: 'bianca', body: 'This comment contains spoilers up to page 220. The library choice at that stage feels like a breath returning.', createdAt: DateTime(2026, 8, 15, 20, 0), spoilerUpToPage: 220),
    ],
    'b3': [
      CommentItem(id: 'cmt6', userName: 'Luna', userSeed: 'luna', body: 'A puzzle box with a velvet lining.', createdAt: DateTime(2026, 8, 11, 11, 0), spoilerUpToPage: null),
      CommentItem(id: 'cmt7', userName: 'Clara', userSeed: 'clara', body: 'This comment contains spoilers up to page 120. The spatial logic of the house is haunting in a calm way.', createdAt: DateTime(2026, 8, 16, 13, 40), spoilerUpToPage: 120),
    ],
  };

  static final selectionSessions = <BookSelectionSession>[
    BookSelectionSession(
      clubId: 'c1',
      mode: BookSelectionMode.voting,
      options: [
        BookSelectionOption(bookId: 'b4', votes: 12),
        BookSelectionOption(bookId: 'b5', votes: 18),
        BookSelectionOption(bookId: 'b6', votes: 7),
      ],
    ),
    BookSelectionSession(
      clubId: 'c3',
      mode: BookSelectionMode.draw,
      options: [
        BookSelectionOption(bookId: 'b1', votes: 0),
        BookSelectionOption(bookId: 'b2', votes: 0),
        BookSelectionOption(bookId: 'b5', votes: 0),
      ],
    ),
  ];
}
